### ISSUE TITLE
uninitialized constant ActiveRecord::DatabaseConfigurations::UrlConfig::ConnectionUrlResolver

### ISSUE THREAD

**Issue by calebfaruki** [malomalo/sunstone#22]
### Description 

Occurs in CI.

### Gemfile
```rb
gem 'rails', '~> 6.1.1'
gem 'sunstone'
```

### Gemfile.lock
```
rails (6.1.3)
  actioncable (= 6.1.3)
  actionmailbox (= 6.1.3)
  actionmailer (= 6.1.3)
  actionpack (= 6.1.3)
  actiontext (= 6.1.3)
  actionview (= 6.1.3)
  activejob (= 6.1.3)
  activemodel (= 6.1.3)
  activerecord (= 6.1.3)
  activestorage (= 6.1.3)
  activesupport (= 6.1.3)
  bundler (>= 1.15.0)
  railties (= 6.1.3)
  sprockets-rails (>= 2.0.0)
...
sunstone (6.1.0.2)
  activerecord (>= 6.1.0)
  arel-extensions (>= 6.1.0)
  cookie_store
  msgpack
```

### Logs
```
Run bundle exec rails db:test:prepare
  bundle exec rails db:test:prepare
  yarn --frozen-lockfile
  bundle exec rails test
  shell: /usr/bin/bash -e {0}
  env:
    RAILS_ENV: test
    RAILS_MASTER_KEY: ***
    DATABASE_URL: ***
rails aborted!
NameError: uninitialized constant ActiveRecord::DatabaseConfigurations::UrlConfig::ConnectionUrlResolver
Did you mean?  ActiveRecord::DatabaseConfigurations::ConnectionUrlResolver
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/sunstone-6.1.0.2/lib/sunstone.rb:51:in `build_url_hash'
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3/lib/active_record/database_configurations/url_config.rb:38:in `initialize'
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3/lib/active_record/database_configurations.rb:262:in `new'
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3/lib/active_record/database_configurations.rb:262:in `environment_url_config'
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3/lib/active_record/database_configurations.rb:253:in `block in merge_db_environment_variables'
/home/runner/work/api/api/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.3/lib/active_record/database_configurations.rb:250:in `map'
```

## Attempts to fix made

Nothing attempted below worked. But worth documenting.

### Lock version to known stable configuration on mainframe project.

No noteworthy change in behavior.

```rb
gem 'rails', '6.1.1'
gem 'sunstone', github: 'malomalo/sunstone', ref: 'cd5f9a92299051f00f46bee319618f9d2ece0f36'
```

**Comment by malomalo** [comment]
I think this has been resolved, it was a Rails 7 issue I if I recall
